version: 1.2
workflows:
  - subclass: WDL 
    primaryDescriptorPath: /workflow/MTtoVCF.wdl
    name: MTtoVCF
  - subclass: WDL 
    primaryDescriptorPath: /workflow/FilterMT.wdl
    name: FilterMT 
   - subclass: WDL 
    primaryDescriptorPath: /workflow/ComputeGeneticPCs.wdl
    name: ComputeGeneticPCs
  
