version: 1.2
workflows:
  - subclass: WDL 
    primaryDescriptorPath: /workflow/MTtoVCF.wdl
    name: MTtoVCF
  - subclass: WDL 
    primaryDescriptorPath: /workflow/FilterMT.wdl
    name: FilterMT 
  - subclass: WDL
    primaryDescriptorPath: /main.wdl
    name: FilterMTAndExportToVCF
  - subclass: WDL
    primaryDescriptorPath: /workflow/LoFCarrierTable.wdl
    name: LoFCarrierTable
  - subclass: WDL
    primaryDescriptorPath: /workflow/HailLoFCarrierTable.wdl
    name: HailLoFCarrierTable
  - subclass: WDL
    primaryDescriptorPath: /workflow/TSVtoHailTable.wdl
    name: TSVtoHailTable
