version: 1.0
workflows:
  - subclass: WDL 
    primaryDescriptorPath: /workflow/MTtoVCF.wdl
    name: MTtoVCF
  - subclass: WDL 
    primaryDescriptorPath: /workflow/FilterMT.wdl
    name: FilterMT 
  
